buildscript {
    apply(from: {
        def searchDir = rootDir.toPath()
        do {
            def p = searchDir.resolve("node_modules/react-native-test-app/android/dependencies.gradle")
            if (p.toFile().exists()) {
                return p.toRealPath().toString()
            }
        } while (searchDir = searchDir.getParent())
        throw new GradleException("Could not find `react-native-test-app`");
    }())
    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        getReactNativeDependencies().each { dependency ->
            classpath(dependency)
        }
    }
}

allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url({
                def searchDir = rootDir.toPath()
                do {
                    def p = searchDir.resolve("node_modules/react-native/android")
                    if (p.toFile().exists()) {
                        return p.toRealPath().toString()
                    }
                } while (searchDir = searchDir.getParent())
                throw new GradleException("Could not find `react-native`");
            }())
        }
        mavenCentral()
        google()
    }
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty("android")) {
            project.android {
                if (project.android.hasProperty("defaultConfig")) {

                    def currentMinSdk = project.android.defaultConfig.minSdkVersion.apiLevel ?: 0
                    def currentCompileSdk = project.android.compileSdkVersion?.toString()?.replace("android-", "")?.toInteger() ?: 0
                    def currentTargetSdk = project.android.defaultConfig.targetSdkVersion?.apiLevel ?: 0

                    defaultConfig {
                        if (currentMinSdk < 24) {
                            minSdkVersion 24
                        }
                        if (currentTargetSdk < 34) {
                            targetSdkVersion 34
                        }
                    }

                    if (currentCompileSdk < 34) {
                        compileSdkVersion 34
                    }
                }
            }
        }
    }
}
